//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonomini_Guido_TPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Message = new HashSet<Message>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
        public string Area { get; set; }
    
        public virtual ICollection<Message> Message { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
