//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonomini_Guido_TPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int StateID { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
