//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonomini_Guido_TPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public int CategoryID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<double> PersistenceTime { get; set; }
        public string ProblemDetail { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public int StateID { get; set; }
        public string TicketUserName { get; set; }
        public Nullable<int> UserInChargeID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
    }
}
